name: CI - Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        env:
          # Prevent Next.js from trying to fetch remote analytics during CI
          NEXT_TELEMETRY_DISABLED: '1'
        run: npm run build --if-present

      - name: Lint
        run: npm run lint --if-present


